# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - odom_base_footprint
    - soulder_base_joint
    - shoulder_forearm_joint
    - arm_forearm_joint
    - roll_arm_joint
    - yaw_roll_joint
    - pitch_yaw_joint
    - gripper_left_pitch
    - gripper_right_pitch
    - left_drive_wheel_joint
    - right_drive_wheel_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_effort_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - soulder_base_joint
    - shoulder_forearm_joint
    - arm_forearm_joint
    - roll_arm_joint
    - yaw_roll_joint
    - pitch_yaw_joint
  gains:
    soulder_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_forearm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_forearm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    roll_arm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yaw_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    pitch_yaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_effort_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_left_pitch
    - gripper_right_pitch
  gains:
    gripper_left_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_right_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1